juju/charmrepo

csclient/csclient_test.go
These fixes were made in response to a review but
weren't in the branch we merged, so this brings them in.
=> csclient: apply later PR fixes

migratebundle/migrate.go, migratebundle/migrate_test.go
This fixes some of the recent openstack bundle problems.
=> migratebundle: fix bundle migration when there are multiple elements in the placement clause

local.go, local_test.go, params.go
With some limitations for now.
=> Add support for retrieving local bundles.

charmstore.go
Also added a comment to ensure that the Close call doesn't
get removed again.
=> CharmStore: fix Get for Windows

charmstore.go
Most other charm store constructors were changed but this one was missed.
=> Fix return type of WithTestMode()

bundlepath.go, bundlepath_test.go, params.go
Add support for reading standalone bundle files.
=> Add ReadBundleFile

csclient/csclient_test.go, dependencies.tsv, migratebundle/migrate.go, migratebundle/migrate_test.go
Also update dependencies to use latest charm package.
=> migratebundle: handle exposing services

csclient/csclient.go, csclient/csclient_test.go
Make sure charmrepo will attempt to upload a multi-series charm when asked.
=> allow upload of multi-series charms

csclient/csclient.go, csclient/csclient_test.go, dependencies.tsv, migratebundle/migrate_test.go
=> Implement PutWithResponse on the csclient.

csclient/csclient_test.go, csclient/params/params.go
Also update the test that relies on the old publish endpoint.
=> csclient/params: add Channel and PublishRequest

csclient/csclient.go, csclient/csclient_test.go
We masked errors from several API calls and didn't provide a way to
tell if an error was an authorization error.
=> csclient: expose API errors

charmstore.go, charmstore_test.go, csclient/csclient_test.go, csclient/params/params.go
=> Revert "Support more channels"

charmstore.go, charmstore_test.go, dependencies.tsv
Also update the Resolve logic to be more agnostic when selecting the best channel.
=> Update charmstore dependency (current 4channels feature branch).

bundlepath.go, bundlepath_test.go, charmpath.go, charmpath_test.go, charmstore.go, charmstore_going_away.go, charmstore_going_away_test.go, charmstore_test.go, csclient/params/error.go, csclient/params/helpers.go, csclient/params/helpers_test.go, csclient/params/package_test.go, csclient/params/params.go, csclient/params/params_test.go, csclient/params/stats.go, export_test.go, legacy.go, legacy_test.go, local.go, local_test.go, package_test.go, params.go, repo.go, repo_test.go, testing/charm.go, testing/mockstore.go, testing/suite.go, testing/testcharm.go
This repository is licenced under LGPL, not AGPL.
=> fix license headers

dependencies.tsv
Update the dep on juju/utils as well.
=> Rev juju/utils to newer revision

csclient/csclient_test.go, dependencies.tsv
Updates the use of resource types from docker to oci/container image.
=> Update resource naming

csclient/csclient.go, csclient/csclient_test.go
This means we can upload an archive to a bunch
of specified channels.
Technically this is a backwardly incompatible change, but
UploadArchive has only been exported for a couple of hours,
so we'll try to overlook that.
=> csclient: add channels argument to UploadArchive

csclient/params/error.go
Also add a go.mod file and update dependencies.
=> add ErrReadOnly

charmstore.go
=> Remove client-side validation for channels when resolving charm URLs

go.mod, go.sum, testing/testcharm.go
The juju/charm/v9 repo was updated so bring that dep in here.
=> Update charm/v9 rev

csclient/csclient.go, csclient/csclient_test.go
Clean merge.
14d7638 (upstream/v6, origin/v6, v6) Merge pull request #168 from SimonRichardson/user-agent-version
=> V6 into master

charmstore.go, charmstore_test.go, csclient/csclient.go, csclient/params/params.go
This PR backports: #181, #182, #183 and #184 to the v6 branch
=> Backport meta method support
