juju/charmrepo

- charmstore_test.go
- migratebundle/migrate.go
- migratebundle/migrate_test.go
This updates it to use the latest version of charm.v6-unstable.
> migratebundle: fix for optional NumUnits

- charmstore.go
- charmstore_test.go
- csclient/csclient_test.go
- dependencies.tsv
Also update to the last charm.v5 and charmstore.v4, and fix test errors due to default permissions changes.
> Forward port ignoring auth errors in Latest.

- csclient/params/error.go
This will be returned as the error when a request cannot be satisfied
because there are too many concurrent requests.
> csclient/params: add ErrServiceUnavailable

- csclient/csclient.go
- csclient/csclient_test.go
- migratebundle/migrate_test.go
This also has the effect of making juju-store login idempotent - it won't acquire
a new macaroon if it doesn't need to.
> csclient: use delegatable-macaroon for login to avoid creating a cookie each time

- charmstore.go
- charmstore_test.go
- csclient/csclient.go
- csclient/csclient_test.go
- csclient/params/params_test.go
- legacy.go
- legacy_test.go
- local.go
- local_test.go
- migratebundle/migrate_test.go
- repo.go
- repo_test.go
- testing/charm.go
- testing/mockstore.go
- testing/testcharm_test.go
Switch to charmrepo.v1.
Extend Interface to include a method for retrieving bundles.
Also remove the deprecated MockCharmStore and other small clean up.
> Support retrieving bundles.

- charmstore.go
- charmstore_test.go
Also update a test so that future regressions can be avoided.
> Propagate error causes when retrieving charms and bundles.

- charmstore_test.go
- csclient/csclient_test.go
- dependencies.tsv
Use charm.v6-unstable with supported-series
Fix a test
Skip mongo tests which use js if no js
> Update dependencies and fix some tests for mongo without js

- bundlepath.go
- bundlepath_test.go
- charmpath.go
- charmpath_test.go
- params.go
NewCharmAtPath and NewBundleAtPath reject relative paths even if they are otherwise valid paths.
We want to avoid ambiguity.
> Reject charms and bundles specified with relative paths

- bundlepath.go
- bundlepath_test.go
- charmpath.go
- charmpath_test.go
- params.go
Add a new BundleNotFound error to match what is done for charms.
Also, when loading  a charm or bundle from a path, check that a supplied path exists before testing if it is relative or not.
> Bundle notfound error

- csclient/params/stats.go
- legacy.go
This is identical to https://github.com/juju/charmrepo/pull/38 but targeted at the unstable branch.
> 001 legacy no escape v2 unstable

- csclient/params/params.go
The endpoint that this pertains to will be this:
This path returns the set of series supported by the given
charm. This endpoint is appropriate for charms only.
```go
type SupportedSeriesResponse struct {
SupportedSeries []string
}
```
Example: `GET precise/wordpress/meta/supported-series`
Response body:
```json
{
"SupportedSeries": ["precise"]
}
```
> csclient/params: add SupportedSeries response type

- bundlepath.go
- bundlepath_test.go
- charmpath.go
- charmpath_test.go
- local.go
On Windows, a call to os.Stat doesn't return a error satisfying os.IsNotExist when the file/path isn't there. It returns a os.PathError with a message like "GetFileAttributesEx.*: The system cannot find the (file|path) specified." So we introduce a helper function and make sure we handle both Windows and non Windows cases.
> Handle path not exists errors on Windows

- dependencies.tsv
Because of the cyclic dependency, the previous dependency was
on a temporary branch.
> update charmstore dependency to mainline version

- charmpath.go
- charmpath_test.go
We require an option to be able to load a charm even if it doesn't support the requested series.
> Add force option to NewCharmAtPath

- charmstore.go
- charmstore_test.go
Add support for querying the supported-series for a charm when resolving. The requires the new charm store.
> Query store for supported series of charm

- charmstore_test.go
- csclient/csclient.go
- csclient/csclient_test.go
- dependencies.tsv
The old tests failed against the charmstore v4 API
(because it has compatibility for v4),
and we shouldn't really have been testing
multi-series charms against the new API anyway.
> csclient: use v5 API

- csclient/params/params.go
- dependencies.tsv
This unifies the entities returned by charm-related with those returned
by other "list-style" endpoints such as /list and /search. MetaAnyResponse
was always wrong here, as the *Response names should be reserved
for responses to individual endpoints.
Technically this is a backwardly incompatible package change (no
change to the HTTP API) so it should cause us to change the charmrepo
version. I'm minded to forget about it because we have no known
client programs that use params.RelatedResponse and submit this
as is.
I'm very willing to accept arguments to the contrary though.
> csclient/params: use EntityResult in RelatedResponse

- bundlepath.go
- charmpath.go
- charmstore.go
- csclient/archive.go
- csclient/csclient.go
- csclient/params/error.go
- csclient/params/params.go
- csclient/params/stats.go
- legacy.go
- local.go
- migratebundle/migrate.go
- params.go
- repo.go
- testing/charm.go
- testing/mockstore.go
- testing/suite.go
- testing/testcharm.go
We should have them anyway, and this will enable CI to know
the correct import path when it's using a feature branch.
> add import comments

- csclient/params/helpers.go
- csclient/params/helpers_test.go
- csclient/params/params.go
This provides a stable over-the-wire format that maps onto the charm/resource.Resource type.
> Add an API data type for resources.

- csclient/params/params.go
Preparation for implementing meta/published in the charm store.
> csclient/params: add PublishedResponse

- csclient/csclient.go
- csclient/csclient_test.go
- csclient/params/params.go
> merge new-channels-model branch

- charmstore.go
- charmstore_internal_test.go
- csclient/csclient.go
- csclient/csclient_resources_test.go
- csclient/csclient_test.go
This will allow us to pass in custom bakery client stuff,
such as agent login. This is a backwardly compatible change.
> csclient: add bakery client to params

- testing/testcharm.go
We add ArchiverTo so we can use the charm.Charm directly in
some APIs, and make the NewCharmMeta call for ease
of creation in table-driven tests.
> testing: add some missing Charm functionality

- csclient/csclient.go
- csclient/csclient_resources_test.go
- csclient/params/params.go
Add  ResourceMeta function to csclient, also remove the revision number from GetResource, since we know the revision (we requested it).  Also flip the name and revision on GetResource, to make it more obvious the revision applies to the resource not the charm.
> Resource get meta

- charmstore.go
- charmstore_going_away.go
- charmstore_going_away_test.go
- charmstore_test.go
- csclient/csclient.go
- csclient/csclient_test.go
- csclient/params/params.go
- legacy.go
- params.go
The CharmStore type has several exported methods that are not part of Interface.  If the goal is to have CharmStore be a strictly conforming implementation then these methods do not belong.  With the addition of CharmStore.Client() we can remove all but one of the methods.  They are either unnecessary or may be implemented as needed in juju core.  The one remaining method is Latest().  This patch moves it to csclient.Client.
Once core has been updated appropriately, the entire charmstore_going_away.go file may be removed.
> Prepare to drop some CharmStore methods.

- csclient/csclient.go
- dependencies.tsv
Update the Login method to pass back any *httpbakery.InteractionError
unmasked.
Note: As interaction might be required on any transaction this might
want to be extended to other methods. Login is the only method where it
is needed currently.
> csclient: pass through *httpbakery.InteractionError

- charmstore.go
- charmstore_test.go
- csclient/csclient.go
We need a reliable way to determine which channel will be used for a charm URL.  The natural place to get that info is when resolving that charm URL.  This patch adds a ResolveWithChannel() method to the CharmStore type.
> Add CharmStore.ResolveWithChannel().

- csclient/csclient.go
- csclient/csclient_resources_test.go
- csclient/csclient_test.go
- dependencies.tsv
We replace some of the mocked tests with tests against the
actual server code.
We also change the ListResources call so that it can work correctly
with the Juju code, simplifying it in the process as discussed online.
> csclient: test resources endpoints for real

- csclient/csclient.go
The meta endpoint is /meta/resources, not /meta/resource.
> csclient: use meta/resources, not meta/resource

- testing/testcharm.go
- testing/testcharm_test.go
These make it easier to create on-the-fly charms with custom metadata.
Taken from charmstore/internal/storetesting.
> testing: add MetaWith helpers

- csclient/params/params.go
This will allow the ingester to become aware of charms that it should
not ingest.
> csclient/params: add CanIngestResponse

- csclient/csclient.go
- csclient/csclient_test.go
We're not guaranteed to get a content-length from our get request, so we can't
guarantee we'll have anything to put in size.
This is half of a fix for https://bugs.launchpad.net/juju/+bug/1628786
> Remove size from ResourceData

- csclient/params/params.go
We want the client to have information about part sizes, etc
when doing multipart uploads. Also change the type name
because it now holds more than just an upload id.
> csclient/params: put more stuff in upload response

- csclient/csclient.go
This makes the client show progress when it uploads to charm stores
that don't support multipart upload.
> csclient: use Progress in single part uploads too

- csclient/csclient.go
- csclient/csclient_test.go
- csclient/params/params.go
- dependencies.tsv
This is an exact copy of PR #128, targeted at the v4 branch instead of v3.
This adds the capability to resume an upload from scratch.
The code does not work against the old version of the charm store
so we depend temporarily on a new version of the charm store
in a feature branch.
> csclient/params: resumable uploads

- csclient/csclient.go
- csclient/csclient_test.go
- csclient/params/params.go
The code as is does not cope with parts that have been omitted.
As we want to be able to do concurrent upload in the future,
we can't always rely on sequential part upload, so we we write
code to cope with arbitrary previously uploaded parts.
> csclient: cope better with upload after partial resume

- csclient/csclient.go
- csclient/csclient_test.go
- csclient/export_test.go
This means we don't have to create huge files in the charmstore-client tests.
> csclient: make MinMultipartUploadSize configurable

- csclient/csclient.go
- csclient/csclient_test.go
This provides an entry point to the docker resource download
endpoint. We want it to fail fast if it's used to download a
non-docker resource, so we change the response parsing
code to check the content type before parsing the content.
As the httprequest package already provides that functionality
(and we're already dependent on that), we use that.
> csclient: add DockerResourceDownloadInfo method

- csclient/csclient.go
- csclient/csclient_test.go
- dependencies.tsv
Previously, despite there being a specific check in
the code for a negative revision, there was also a check
that the revision was *not* negative, so it wasn't
possible to download the currently published revision
for a resource. Now it is.
> csclient: allow download of latest resource

- csclient/csclient.go
- csclient/csclient_test.go
Technically this is a backwardly incompatible change
but it's a very recent change so no-one will be using the API.
La di da.
> csclient: add revision number to resource download info

- csclient/csclient.go
- csclient/csclient_test.go
We'd like to know how big a resource is before downloading it.
> csclient: return resource size

- csclient/csclient.go
- csclient/csclient_test.go
- go.sum
When ContentLength is zero, net/http treats the content length
as unknown unless req.Body is nil, which meant that we'd
get an error when uploading a resource because the charmstore
server requires an explicit Content-Length.
> csclient: allow upload of zero-length resources

- csclient/params/params.go
This will be a base-entity-oriented endpoint in the charmstore to allow
getting all permissions on all channels on a charm even when we don't
know a specific revision.
> csclient/params: add AllPermsResponse

- csclient/params/error.go
This will be returned from charmstore endpoints when the charm store is in read-only mode.
> add ErrReadOnly

- charmstore.go
- charmstore_test.go
Prior to this change, the client could enforce a particular channel for
*all* lookups. However, we the recent charm.v6 changes we are now able
to specify a per-application channel. As a result, we need a new resolve
method whose signature allows us to specify the preferred channel to
use.
If no channel is specified, the clients forced channel (if provided)
will be used as before and then the lookup code will fall back to
selecting the best (most stable) channel version based on the metadata
obtained by the store.
Note: as the `CharmStore` type methods are not included in any interface
exposed by this package this is a backwards-compatible change.
> Add charmstore method to resolve charm/bundles with a preferred channel

- charmstore.go
- csclient/csclient.go
- csclient/csclient_test.go
This PR adds a `MetaWithChannel` method to the charmstore client which allows us to inject a `channel` request parameter to charmstore metadata queries. 
The current implementation allows users to plug a channel into the client (via a client attribute) which then gets _auto-injected_ into all outgoing requests. This is not suitable for our per-charm channel use-case where we potentially need to specify different channels for each metadata lookup request. 
Unfortunately, the injection happens deep in the request making code (!!!) and obviously we cannot tweak the shared channel attribute as that would make the client not safe for concurrent use.
With that in mind, and with the goal to make the change as simple as possible, I opted to add the new `MetaWithChannel` method which injects the …
> Allow client users to specify channel when querying metadata

- testing/charm.go
This change enables us to create repos from any path.
With some changes to the way we test charms, we want them to reside in a tmp directory. Thus we need a way to tell which path we use instead of using the relative one.
> adds additional way to create a repo

- testing/charm.go
Initially, https://github.com/juju/charmrepo/pull/156 was put forward because we changed the way how charm vcs were defined. 
Which led to failure in some test-cases for juju, because some charms are versioned inside of juju. This led to "wrong" version expectations. 
Another later change made the `pr 156` obsolete by changing the call structure of the charms. https://github.com/juju/charm/pull/298
Therefore we can safely remove this code.
> charm testing: remove dead code

- csclient/csclient.go
- csclient/csclient_test.go
The following sets a user-agent for the client so that when hit a server
we can identify where the source of the request is comming from.
This should hopefully help with statistical analysis at a later date.
> User-agent

- charmstore.go
PR #157  introduced client-side validation for the channel argument when resolving charm URLs. The validation was added as a nice-to-have feature that leveraged the already present [csclient/params.ValidChannels](https://github.com/juju/charmrepo/blob/v4/csclient/params/params.go#L72) map to avoid unnecessary roundtrips to the server.
Unfortunately, this addition seems to break applications that use charmrepo.v4 assuming that the validation will always be performed by the server. To address this issue, this PR removes the aforementioned validation code.
Fixes: https://bugs.launchpad.net/juju/+bug/1862091
> Remove client-side validation for channels when resolving charm URLs

- csclient/csclient.go
- csclient/csclient_test.go
The default client should allow us to override the User-Agent value so
that the application can send the same consistent User-Agent across
requests.
> Allow custom user agent value

- charmstore.go
- csclient/csclient.go
- csclient/csclient_test.go
- csclient/params/error.go
- csclient/params/params_test.go
- go.mod
- go.sum
lxd doesn't support go mod so revert to using gopkg.in version of macaroon bakery
> Use gopkg.in/maaroon-bakery.v3 instead of github.com/go-macaroon-bakery/macaroon-bakery/v3

- charmstore.go
- charmstore_test.go
- csclient/csclient.go
This is a followup to #181 which exposes the `GetFileFromArchive` method via the `CharmStore` wrapper type that Juju uses. 
In addition, the PR also adds tests which exercise both the `CharmStore` and the underlying client implementation when `GetFileFromArchive` is invoked.
> Expose GetFileFromArchive through the CharmStore type

- csclient/params/params.go
The following removes the debugstatus dependency from the csclient. This
will ensure that we don't accidentally call the init function within the
juju/httpprof package.
Additional work might be required to remove that init function from
there as well, but we'll have to see.
> Remove utils/debugstatus dependency
